name: Fetch Real Estate Data Daily

on:
  schedule:
    # 每天北京时间上午9点运行 (UTC时间1点)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Fetch real estate data
      run: npm start

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        # 检查是否有文件更改
        if git status --porcelain | grep -qE 'data/'; then
          git add data/
          git commit -m "Update real estate data [Daily automated update]
          
          - Updated daily data: $(date +%Y-%m-%d)
          - Updated monthly data: $(date +%Y-%m)"
          git push
          echo "Changes committed and pushed"
        else
          echo "No changes to commit"
        fi